### ISSUE TITLE
I find lazy_kernel on ooneplus-5t min_brightness should be bigger than 302

### ISSUE THREAD

**Issue by kouzijiao** [ederevx/lazy_kernel_oneplus_msm8998#1]
Today,I use your lazy kernel in my miui12 based on pie.I find proc/filicker/min_brightness file is readonly,it's value is 90,but this value in 90 is not work formally.In other dc kernels based on weeb.I find min_brightness is 370 on  oneplus 5t(min_brightness is 66 on  oneplus 5). This value can work formally.Can you recompile this kernel for me?My Email is kouzi0426@foxmail.com

**Comment by ederevx** [comment]
Please ping me in our kernel support group so that we could discuss this further.

Link: https://t.me/lazykernel
